### ISSUE TITLE
Problems installing the package

### ISSUE THREAD

**Issue by KimAHaugland** [sykdomspulsen-org/spread#12]
Hi,
I am trying to install this package in order to explore the model further (as part of my PhD project).
However, no matter which way I try to install it, I get the error: "ERROR: dependency 'fhidata' is not available for package 'spread'".

I am wondering if there is a file missing?

Best regards,
Kim Haugland

**Comment by raubreywhite** [comment]
Sorry about this. The dependency issues have now been fixed.
